version: '3'

services:
  db:
    image: mariadb:10.4.10-bionic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
     - db:db
    ports:
      - "8080:80"

  omekas:
    depends_on:
      - db
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/custom/:/var/www/html/themes/custom/
    restart: always
